### ISSUE TITLE
Implement creation of new datasets via importing ISO-compliant XML files

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#105]
We need to support the creation of new EMC datasets by means of letting users import them from previously-existing XML files, as long as they are ISO 19115 compliant

Implementation shall allow users to upload a batch of xml files, which will be imported asynchronously. When the import is finished, the user shall receive an email notification with the status of the import and with notice of any failures

**Comment by ricardogsilva** [comment]
It would be good if the implementation prepares for multiple formats, even if the initial PR only supports ISO 19115 XML files.

**Comment by gubuntu** [comment]
'import' = 'upload'

more than being ISO 19115 compliant, they must be SANS 1878 compliant

the workflow must handle one or more files

minimum mandatory field compliance should result in success (creation of a private record that enters the usual approval process)

non-compliance in either format or content should result in an informative error response per file so the user knows what to fix before trying again

**Comment by Mohab25** [comment]
@Samweli @Fanevanjanahary please take notes as this may affect your work
this issue is related to #290, the minimum set of fields required to be SANS 1878 is defined as follows (few fields needs more clarification to check their suitability for EMC):
~~~py
DATASET_MINIMAL_SET_OF_FIELDS = [
    "title",
    "name",
    "metadata_standard_name",
    "metadata_standard_version",
    "notes",
    "purpose",
    "status",
    "metadata_point_of_contact-0-organizational_role",
    "reference_date",
    "iso_topic_category",
    "owner_org",
    "private",
    "dataset_language",
    "metadata_language",
    "dataset_character_set",
    "lineage-0-lineage_statement",
    "lineage-0-process_step_description",
    "distribution-0-distributor_contact",
    "maintainer",
    "spatial",
    "equivalent_scale",
    "spatial_representation_type",
    "spatial_reference_system",
    "metadata_date_stamp",
]
~~~


as per the ticket, one or many files can be uploaded at once , if a file contains the minimum mandatory set of fields, the dataset will be created out of the xml file file, regardless of it being uploaded as a single file or within a set of files, each file is checked for the minimum set, maximum set and empty file checks, the following error and info messages appears with each corresponding cases:
	1. when there is a field not covered by the maximum set of fields, the dataset creation is rejected from the xml file, and the system returns a message states the violating field name and the file name that contains it (to address multiple files uploads), it would appear both if the user is using the UI or uploading via CLI (using the xml_parser blueprint url), the message reads as "field "file_name" in the file "file_name" is not within the maximum set of allowed xml fields", the maximum set of fields is defined at the end of this comment, the following images illustrate a case where a maximum check is violated (UI and cli).
![UI showing maximum fields check violated](https://user-images.githubusercontent.com/58084234/187399743-abbfecb6-1f87-44bb-be76-5f1191cca02d.png)
![cli showing maximum fields check violated](https://user-images.githubusercontent.com/58084234/187400256-a13d7b98-71a8-48e4-a96b-ccc1b018d1d1.png)

	2. if there is a field required by the minimum set of fields and not provided with the uploaded xml file(s), the system sends a message stating the required field and the file it's in, it reads as "field "field name" is a required field, missed in file "file name"", images below illustrate a case where a minimum field is missed (UI and cli).
![Ui showing minimum fields check violated](https://user-images.githubusercontent.com/58084234/187400953-34d7e12b-9cfc-4a51-8e3f-d4cc1ec1ae52.png)
![cli showing ](https://user-images.githubusercontent.com/58084234/187401058-aba71215-47c0-412f-9164-dc7022061115.png)
	3. if the xml file is empty the system sends an error message as "file "filename" is empty!", this is also the case where the file has only one opening dataset tag without content, the following images illustrate the behavior (UI and cli)
![empty file response](https://user-images.githubusercontent.com/58084234/187512260-3f5a00ed-6e95-48e5-8e44-cbf5224b6095.png)
![empty file response](https://user-images.githubusercontent.com/58084234/187512267-c7bd11ae-f217-4c3c-9faa-c68d38271bf1.png)	
	4. if there is a case where parsing xml file is not correctly done for unknown reasons, the system sends general message reads "something went wrong during dataset creation"
	5. when one package is created, a message of "package "package title" were created" is returned.
	6. when all the packages are created (in case multiple files are uploaded without problems) the system returns "all packages were created" message
	the following images shows where all the packages are created
![all packages created without errors](https://user-images.githubusercontent.com/58084234/187513104-f8fb0e00-d202-4bae-baa8-736ae7183f18.png)
![all packages created without errors](https://user-images.githubusercontent.com/58084234/187513127-2f7b0ba3-2281-4362-bb7e-f18192fb7f2b.png)
7. when there are multiple files uploaded, and some of them has errors while others are created, this is reflected both in the UI (via multiple messages)  and cli, the cli return a list of info_msgs and error_msgs, (msgs = messages)
![multiple files upload ](https://user-images.githubusercontent.com/58084234/187514177-68d5db04-01d8-4aae-816f-37e7ad6c9f13.png)
![multiple files upload ](https://user-images.githubusercontent.com/58084234/187514191-3cabdf8d-bf7e-4599-aea4-1979a9c495eb.png)
8. when files are uploaded, an email will be sent to the creator holding both info messages and error messages, the following image illustrates an email sent to my personal gmail account, this needs the testing, staging and production sites to enable SMTP services, @tharanathkartoza please take notes
![email sent once upload is done](https://user-images.githubusercontent.com/58084234/187514699-863c4240-eff2-4849-abbc-135eae29f100.png)

the maximum set of fields is as follows:
~~~py
DATASET_FULL_SET_OF_FIELDS = [
    "title",
    "name",
    "featured",
    "metadata_standard_name",
    "metadata_standard_version",
    "notes",
    "purpose",
    "acknowledgement",
    "status",
    "metadata_point_of_contact-0-individual_name",
    "metadata_point_of_contact-0-position_name",
    "metadata_point_of_contact-0-contact_point_address_city",
    "metadata_point_of_contact-0-contact_point_address_administrative_area",
    "metadata_point_of_contact-0-contact_point_postal_code",
    "metadata_point_of_contact-0- contact_point_electronic_mail_address",
    "metadata_point_of_contact-0-organizational_role",
    "owner_org",
    "private",
    "reference_date",
    "iso_topic_category",
    "sasdi_theme",
    "tag_string",
    "license_id",
    "url",
    "version",
    "dataset_language",
    "metadata_language",
    "dataset_character_set",
    "lineage-0-level",
    "lineage-0-lineage_statement",
    "lineage-0-process_step_description",
    "lineage-0-process_step_datetime_from",
    "lineage-0-process_step_datetime_to",
    "lineage-0-processor_individual_name",
    "lineage-0-processing_owner_org",
    "lineage-0-processor_position_name",
    "lineage-0-processor_address_city",
    "lineage-0-processor_address_administrative_area",
    "lineage-0-processor_postal_code",
    "lineage-0-processor_electronic_mail_address",
    "distribution-0-distributor_contact",
    "distribution-0-distribution_order_process",
    "distribution-0-units_of_distribution",
    "distribution-0-distribution_online_source",
    "maintainer",
    "maintainer_email",
    "maintenance_information-0-maintenance_and_update_frequency",
    "maintenance_information-0-maintenance_date_of_next_update",
    "maintenance_information-0-user_defined_maintenance_frequency",
    "maintenance_information-0-update_scope",
    "maintenance_information-0-update_scope_description",
    "maintenance_information-0-maintenance_notes",
    "spatial",
    "equivalent_scale",
    "spatial_representation_type",
    "spatial_reference_system",
    "temporal_reference_system",
    "reference_system_additional_info-0-temporal_extent_period_duration_from",
    "reference_system_additional_info-0-temporal_extent_period_duration_to",
    "minimum_vertical_extent",
    "maximum_vertical_extent",
    "metadata_date_stamp",
]
~~~

**Comment by Mohab25** [comment]
@Samweli note the maximum and minimum sets are defined in constants.py, i believe this is particularly important for you because the DCPR requests won't be converted to EMC datasets if the minimum set given is not covering the new one.

**Comment by gubuntu** [comment]
@Mohab25 so is this done? What is it waiting for?

**Comment by Jeremy-Prior** [comment]
Running curl command from terminal says the metadata records were successfully created:
![1_Created](https://user-images.githubusercontent.com/100694811/204532243-d4fee7fa-a14e-4405-ae08-ec810640f762.png)

However, the records don't appear on the site:
![2_NotOnSite](https://user-images.githubusercontent.com/100694811/204532377-563c0a71-704b-4222-9eb4-f2601344cdef.png)

This is one of the XML files uploaded containing all the mandatory SANS 1878 fields:
![3_ExampleXML](https://user-images.githubusercontent.com/100694811/204532607-c2c5d73c-6e9c-4916-b650-82011f8c4ab0.png)

**Comment by Jeremy-Prior** [comment]
Running the correct curl command with updated XMLs based on @Mohab25 's example dataset:
![4_CreationWorks](https://user-images.githubusercontent.com/100694811/204800487-77f58def-fea7-4cc3-b627-4eee10af2bf6.png)

The new metadata records reflect on the site:
![5_ReflectedOnSite](https://user-images.githubusercontent.com/100694811/204800623-0e6c8628-06c0-4976-ace9-90e032cff35d.png)
