### ISSUE TITLE
File format not provided when downloading metadata file

### ISSUE THREAD

**Issue by seabilwe** [kartoza/ckanext-dalrrd-emc-dcpr#235]
When downloading the metadata file, the file format is not specified, for example, `.xml`
![file-format-not-specified](https://user-images.githubusercontent.com/56301949/178263264-7aa3b2df-e268-4d6a-a3ca-a603bb878865.gif)

**Comment by gubuntu** [comment]
Furthermore, the filename should be much more user-friendly e.g. match the title

**Comment by Mohab25** [comment]
@Fanevanjanahary i think this is related to the #291, please give it a test after uploading this file, both issues are related to the docker storage which should be working after tharanath last updates, bear in mind that we shouldn't store any files in the system, rather, links should be given to different resources so the user can track and download them elsewhere.

**Comment by Jeremy-Prior** [comment]
I tested by uploading different formats and, then downloading the files to check format that the format was provided during download and that it was the same as the upload format.


**GeoJSON**
Upload:
![2_UploadAsGeoJSON](https://user-images.githubusercontent.com/100694811/201666281-d70e5323-94aa-4097-8e14-9739c976d7dc.png)
Download as same format:
![2_DownloadAsGeoJSON](https://user-images.githubusercontent.com/100694811/201666457-506d8a6a-d399-4f72-9f47-5d7c48d97fdf.png)

**Zip Folder**
Upload:
![3_UploadAsZip](https://user-images.githubusercontent.com/100694811/201666574-cc7d6188-487f-456a-b5ea-fcd0b1b9e2dd.png)
Download as same format:
![3_DownloadAsZip](https://user-images.githubusercontent.com/100694811/201666661-29202349-d1e3-4199-afb3-4d9602ac1013.png)

**Shapefile**
Uploaded a shapefile:
![1_UploadAsSHP](https://user-images.githubusercontent.com/100694811/201666773-e682d7c8-eda6-4e81-a7de-a2cb28b83989.png)
But it downloaded as a ".qgs" file. Unsure why this happened, but think it may be because I only uploaded the .shp without the .shx and .dbf files :
![1_DownloadAsQGS](https://user-images.githubusercontent.com/100694811/201666977-bd095123-ef2e-4b88-8104-5a37e3a782b5.png)

**Comment by gubuntu** [comment]
there is not supposed to be any upload facility so it should be disabled if there is any. 

And this issue is about downloading the metadata record, please just address that

**Comment by Jeremy-Prior** [comment]
> there is not supposed to be any data upload facility so it should be disabled if there is any.
> 
> The only upload facility should be for metadata xml records themselves.

@gubuntu You can currently upload any format of data file when creating a metadata record on the site, provided it is a small enough file: 
![image](https://user-images.githubusercontent.com/100694811/203719517-daa8a9e5-7bd2-4a9a-b7ec-0fc1f637f734.png).

The site encourages CSV, XML, or JSON formats but any format can be specified:
![image](https://user-images.githubusercontent.com/100694811/203723533-0638f564-ae19-4e8e-88c9-681e91b0173a.png)

@Mohab25 Is it possible to limit users to only uploading xml files?

> And this issue is about downloading the metadata xml record (not a data file like json or shp), please just address that

On a record where only an XML file has been uploaded as the associated data, the format is provided when a user clicks download and then saves the webpage: 
![4_DownloadXML](https://user-images.githubusercontent.com/100694811/203724798-2c14c709-70ba-4e41-9813-5c27bc414d78.gif)

> And the downloaded xml must of course be SANSA 1878 compliant

The SANSA 1878 compliancy relies on the XML file a user uploads as you can only download the associated Data and Resources not the entire Metadata Record:
![image](https://user-images.githubusercontent.com/100694811/203725329-e2214dcd-7909-46de-88a3-ebc94b7e15e1.png)

**Comment by gubuntu** [comment]
please keep to the topic of this issue - it is about downloading the metadata file, not about downloading resources or anything else. 

The user HAS TO be able to download the full, compliant XML metadata record (including resource links in the appropriate fields)

For discussion on uploading and downloading other files see #379

**Comment by Mohab25** [comment]
per #379 the EMC is a "metadata clearinghouse only", uploading and downloading files from  the system is disabled, see comments on #379

**Comment by Jeremy-Prior** [comment]
Download facility removed:
![5_DownloadDisabled](https://user-images.githubusercontent.com/100694811/204466113-15f3a94c-d6b7-4a1e-88e5-000f11d360d5.png)
