### ISSUE TITLE
Suggest changing Log in to Sign in

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#244]
I suggest changing "Log in" to "Sign in". Log in in my view makes the help documentation harder to read. In the case of this sentence "make sure you have logged in to make changes to your profile" vs "make sure you have singed in tom make changes to your profile".

**Comment by Mohab25** [comment]
@gubuntu  @EliVolsch , we can afford to change "login" that appears in the login page title and the login button, also in the navigation bar (see attached screenshot), but we can't afford to change "login" that appears in the url, the issue here with CKAN, login action goes several layers deep and affects other places, although we can  track down all these actions, we don't want any surprises at this stage, if the following modifications are sufficient, we can go ahead with them,
@Fanevanjanahary what are your thoughts.
note: don't bother about the title in  the browser tab, that can be changed too, 
![Screenshot from 2022-09-22 12-17-29](https://user-images.githubusercontent.com/58084234/191721965-2d11d489-d987-4e6f-ba3b-e230f640630f.png)

**Comment by Mohab25** [comment]
i'm closing this as there is no feedback, feel free to reopen it

**Comment by EliVolsch** [comment]
@Mohab25 These modifications are sufficient. I dont believe users will be double checking the url so no need to cause unexpected issues down the line.

**Comment by Jeremy-Prior** [comment]
@Mohab25 Has this just not been implemented on the testing site or has it been decided that it should stay as "Log in"?

![login](https://user-images.githubusercontent.com/100694811/202115113-1e8bc8d6-3e56-4653-903a-2d66d9eb1e62.png)

**Comment by gubuntu** [comment]
'Log in' is pretty standard so unless this comes from the client I'd leave as is
