### ISSUE TITLE
Language selector not translating all text on page

### ISSUE THREAD

**Issue by EliVolsch** [kartoza/ckanext-dalrrd-emc-dcpr#258]
For the example I have changed the language to Japanese in order to better present which items are translated vs the ones that's not.
This is the result:
![EMC_Language](https://user-images.githubusercontent.com/107027990/180981126-f514a8ac-f124-4009-a18b-bb0609021fbf.png)

Vs what it looks like using edge translator:
![EMC_Translation1](https://user-images.githubusercontent.com/107027990/180981326-1e829760-5d4b-4351-b5f9-80a4c0521807.png)

**Comment by Mohab25** [comment]
@gubuntu @EliVolsch this issue is mistakenly described as a bug, it's rather related to the translation process in CKAN, at first i though it is a trivial issue, but took a significant amount of time to have a partial implementation, CKAN translation process can either rely on translations provided by CKAN translation team  - which affect site with each new release -  or websites based on CKAN can provide their own translations, this local translation can either go to the CKAN source or to an extension, it's also can be created manually or using a software as Transifex (which is used by the CKAN translation team), each has it's own workflow, as we are adding CKAN as a dependency with the docker stack, internationalization was added to the extension instead of the source code,  also as we are using poetry instead of the built-in setup.py files, i had to go to [babel](https://babel.pocoo.org/en/latest/index.html) and moved code around, babel is the main python dependency that is used to create translations from python code, i had to first create translations in local host, but the process can be semi-automated afterwards, in short here is how it works:
1. translation strings -pretty much everything that we want to translate -  are extracted out of the source code (python and html templates) with babel extractors, in order for this to happen these strings needs to be marked in the source code (e.g. using something as _("Welcome to the EMC-DCPR ")) , please refer to https://docs.ckan.org/en/2.9/contributing/string-i18n.html
((@Samweli , @Fanevanjanahary please remember to add string internationalization mark to each static string we write, visit the second link below)
3. POT file is generated from the extraction procedure, this file holds all the extracted strings with a section in which the user can provide a translation for each string.
4. the POT file is copied into certain locale (e.g. en/LC_MESSAGES/ckanext-extension_name.po) - notice the extension rename.
5. a translation is given to each and every string in the file, manually or wtith help of a software as Transifex
6. the local po files are compiled into .mo files.
7. CKAN ITranslation interface is used with the extension. 

the following results are used as a demo for Japanese language, the translation can go as deep as the actions happening in the website:

![translation results -1 ](https://user-images.githubusercontent.com/58084234/192116480-49a56120-6268-4b45-86b5-b79cb75fb108.png)
![translation results -2](https://user-images.githubusercontent.com/58084234/192116483-5ea63edc-c458-467c-9053-fbccb980dbb1.png)
![translation results -3](https://user-images.githubusercontent.com/58084234/192116484-3f45d13f-3bd2-4c75-a4c7-dae925bfa1ee.png)
![translation results -4](https://user-images.githubusercontent.com/58084234/192116485-8c52b3a0-ddfb-4eac-a32d-60c139ac14e8.png)
![translation results -5](https://user-images.githubusercontent.com/58084234/192116486-c747d4ec-8dd7-470b-b44e-c4400b313e3a.png)

practically it's very hard to add translations to all languages at once, we need to choose only a subset of languages and add translations to each string in the website for them, @seabilwe please take notes,  

to see how a translation file looks like visit (https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/blob/main/ckanext/dalrrd_emc_dcpr/i18n/ja/LC_MESSAGES/ckanext-dalrrd_emc_dcpr.po), 

links:
https://docs.ckan.org/en/2.9/contributing/i18n.html
https://docs.ckan.org/en/2.9/contributing/string-i18n.html
https://docs.ckan.org/en/2.9/extensions/translating-extensions.html
https://docs.ckan.org/en/2.9/maintaining/configuration.html#internationalisation-settings

**Comment by gubuntu** [comment]
providing translations is not in scope so can we simply disable?

**Comment by Mohab25** [comment]
removed the added translation, we can't disable the translated parts that comes by default with CKAN, could try to remove the i18n if CKAN wasn't used as a dependency

**Comment by Fanevanjanahary** [comment]
Or can we remove the choice language in the footer?
