### ISSUE TITLE
Confirm or modify DCPR workflow

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#276]
The DCPR request workflow must follow the correct paths for form E1 requests and form E2 notifications as per this extract from the updated drawio diagram below. Confirm that this workflow is in place with screenshots else modify the workflow to comply. 

Furthermore, the different workflows must be queryable in site analytics / statistics. 

<img width="626" alt="Screenshot 2022-08-08 at 11 51 15" src="https://user-images.githubusercontent.com/496911/183390823-a2eed925-bc8a-4e44-be28-07a05111c96d.png">

**Comment by Samweli** [comment]
@gubuntu the proposed system design architecture document outlined that the DCPR request workflow would merge Form E1 and E2 into a common DCPR request type form, this is because there is/was a small difference between Form E1 and E2.

As a result the current EMC form for creating DCPR request achieve the same by letting user specify if they are data custodian via Organization custodian option in the merged form. 

See System Design Architecture section 3.2.1.

Current DCPR request form with field for specifying whether owner is data custodiam
![data_custodian](https://user-images.githubusercontent.com/2663775/189878879-714d19f2-3d92-4fe9-9196-cfee8bbf6c65.png)

**Comment by gubuntu** [comment]
@vutomim I'm happy that this is sufficient to distinguish Forms E1 and E2. Please comment or close if you agree.

**Comment by vutomim** [comment]
Why are we moving away from the proposed mock-ups? I thought we had agreed to implement it in that line

**Comment by Mohab25** [comment]
@Samweli @gubuntu as per email exchange with @vutomim, it's the UI what needs to be changed to match the mockups, quote "I am not too worried about the background process as that has already been presented and accepted. What I am referring to now is that the UI should reflect what was proposed and accepted. It would be unacceptable if we present a system that doesn’t reflect what was approved on the front-end."
@Samweli @Fanevanjanahary  we would need to meet to decide how to separate the functionality from the current UI implementation and re-implement things with two forms.

**Comment by Mohab25** [comment]
this has been implemented, the system now exhibit different workflows and different pages for E1,E2 forms.
 
![Screenshot from 2023-02-16 08-36-34](https://user-images.githubusercontent.com/58084234/219287656-ec8ed9ee-e562-460a-a6b2-9e22d4baa48d.png)
![Screenshot from 2023-02-16 08-37-16](https://user-images.githubusercontent.com/58084234/219287661-2b97a198-235d-4426-81da-c375dd42d8a3.png)
![Screenshot from 2023-02-16 08-37-41](https://user-images.githubusercontent.com/58084234/219287669-17c75b13-c5fc-4c94-9a81-d44faf03c5c6.png)
