### ISSUE TITLE
show version in footer or header

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#341]
UA testers need to note which version they are testing. So they need to see the version. 

On the staging site (main branch) show a nice version label in the header or footer, like 'RC0.1' - follow best practice version naming conventions.

In the production site (tagged release) show the release tag label.

**Comment by Mohab25** [comment]
@gubuntu before going to implementation, for the production site the tag can come from github, but i don't see how the staging can have a footer that is not hard-coded, any ideas ?

**Comment by gubuntu** [comment]
ask around in our dev COP channel - we should have or establish standard practice around this. We can put in the commit hash but that won't be nice for a user to note. Unless we do actually tag RCs to deploy to staging and proper versions to production?

**Comment by Mohab25** [comment]
@gubuntu your final suggestion is a good approach, we would proceed with the usual semantic versioning, v0.0.1-rc for release candidates and v0.0.1 for releases, the size is 2 here because first the opertaion will be extracting version from GH and put send them to deployed containers then use them with the site.

**Comment by Mohab25** [comment]
@gubuntu please check  #371 for more on the simver applied, in order to complete this issue we need a token for github accessibility assigned to the current account which has full accessibility to the repo (or enough access to tags specifically), the code calls github api to get the latest tags and updates the site accordingly, also @tharanathkartoza we need a cron job to run the following file every 10 minutes to check if there is an update on the github tag, 
`/home/appuser/app/ckanext/dalrrd_emc_dcpr/get_releases.py`
@gubuntu this issue seemed trivial at first, but was a bit convoluted, first approach was to get the latest release and candidates through git actions and then persist them to the docker container which is created after each push to "development" or "main" branches, this deemed to bit confusing as to change a file in the repo from an action the bulk of suggestions was to make another push to the repo from within the action, our current stack already takes about 1 hour to complete creating docker images and push them to dockerhub, the second approach was to fetch the data from github with js files, but github applies a limit over it's api (5000 requests per hour), although i don't know if the emc will be visited by this number of users every hour, to avoid this cap, i've tried to approach it as there is one python script which is called every 10 minutes (the cron job above) which fetches the latest versions, and writes to a file, then this file is read from the site, this will total to 6 calls every hour to get the latest versions.
reflecting on this, such issues that represent more of a convenience are better left for next phase not this one.

**Comment by gubuntu** [comment]
Can the release tag info from which the image was built not be made available in the docker image itself (though I think that might be what you are saying as one of your options above). 

semver no simver?

I don't think this is just a convenience. I think it should be standard in all our projects (did you check how we've done it in other projects before?) and it's necessary for testing and error reporting. 

Which user will need the token? And will you make a toekn request? (I don't see one yet in Settings)

**Comment by Mohab25** [comment]
@gubuntu is the kartoza account is up ?

**Comment by Mohab25** [comment]
Kartoza GH account is used and creds are injected as environment variables, a note for testing this is that tester should create a new release in GH and see if the release changes after a while (ask tharanath about the time interval in which the script runs).

**Comment by Jeremy-Prior** [comment]
Version showing in footer of staging site
![VersionInFooter](https://user-images.githubusercontent.com/100694811/208624476-f121eed7-979c-4b34-8e55-73b4cf3e3466.png)
