### ISSUE TITLE
Adding a dropdown menu options to the 'Help' button 

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#358]
Adding a dropdown menu options to the 'Help' button so that there can be multiple help documents under the main Help option.
![image](https://user-images.githubusercontent.com/98025261/198249980-d9236bc9-0b45-452f-ae60-d713ddf8e3a9.png)

**Comment by gubuntu** [comment]
@ThiashaV you moved this to In Progress 11 days ago. It should be up to @Fanevanjanahary to put it there when she's actually working on it otherwise it appears she's been workign on it for nearly two weeks. 

Hopefully @Fanevanjanahary #368 you made today fixes this? It's high priority, please get it deployed asap.

**Comment by ThiashaV** [comment]
Drop down is implemented and in a user friendly order:

![image](https://user-images.githubusercontent.com/98025261/203927774-4e7f973c-499f-4d94-b1aa-22a66eec0663.png)
