### ISSUE TITLE
spatial search map fixes

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#370]
- [x] the map components take a while to load on first page load
- [x] the 'expand' control needs a tooltip to say what it's for
- [x] when expanding, the map should match the width of and align with the other page elements, which it doesn't do right now
- [x] there should not be blank space when the map expands. It should centre on SA or wherever the user has zoomed and continue with map content to the edge of the canvas (like it does after you click the edit icon)
- [x] after digitising a rectangle, the apply button overlaps the section below, please polish the placement
- [x] the thick blue boundary style doesn't look great
- [x] each layer should be mutually exclusive i.e. radio buttons rather than check boxes. Right now it's possible to draw all four layers which gets messy
- [x] how does one do a proximity search? (RF04c)

**Comment by Mohab25** [comment]
@gubuntu currently my commnet on the first issue is that we are constrained by the deployment and can't modify directly ckan spatial extension, the code first wait for it to load then applies the necessary changes (adding search spatial boundaries, adding buffer for proximity - the last circular button), caching might help to speed load time though

**Comment by Mohab25** [comment]
replacing spatial files with lighter versions seeded up the page load, added "search with rectangle bound" as title for the edit button, and "search with circular buffer" for circle edit, added  radio buttons instead of checkbox.
![search with rectangle bound](https://user-images.githubusercontent.com/58084234/202950865-42e49a10-3e66-4ec8-8bd5-06921891df57.png)


![radio button instead of checkbox](https://user-images.githubusercontent.com/58084234/202950877-ee49da7d-686d-4070-9b6c-80adf07c2086.png)

**Comment by Mohab25** [comment]
@gubuntu " when expanding, the map should match the width of and align with the other page elements, which it doesn't do right now", this is the default behavior of ckanext-spatial, i've modified it so the map goes edge-to-edge with the content (following screenshot),  if this is not what you mean, please give more clarification.

![map view expansion](https://user-images.githubusercontent.com/58084234/204101344-14a52587-0bf8-4284-ba3b-ceb9b525d934.png)

**Comment by Mohab25** [comment]
" there should not be blank space when the map expands. It should centre on SA or wherever ..."  please see https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/pull/383#issue-1465213615

**Comment by Mohab25** [comment]
"after digitising a rectangle, the apply button overlaps the section below, please polish the placement"
![apply button fix](https://user-images.githubusercontent.com/58084234/204102542-1eeaf02f-c910-4400-9d30-3dc48d1cb7b5.png)

**Comment by Mohab25** [comment]
"the thick blue boundary style doesn't look great" - mock or inspiration please @seabilwe @Jeremy-Prior @ThiashaV 
" each layer should be mutually exclusive i.e. radio buttons rather than check boxes. Right now it's possible to draw all four layers which gets messy"
applied with the previous request
![radio buttons](https://user-images.githubusercontent.com/58084234/204108119-f21e971c-d20f-4009-b687-3cc360181db9.png)

"how does one do a proximity search? (RF04c)" 
using the circular button which creates a circle buffer for the search

![circular search](https://user-images.githubusercontent.com/58084234/204108216-65a132ab-f7c3-48c2-a141-f3ad040e52a1.png)


few issues that needs enhancement:

1. if the rectangle button clicked more than once it doesn't move out the zoomed search and disable the drawer, and even if cancel is clicked the rectangle drawer will still be enabled until the user draws a rectangle then click cancel, this is a default behavior of ckanext-spatial that i spent quite a time to modify without results, unlike previous work so far to enhance the behavior of the extension which is based on adding events after the map is loaded, accessing indefiniter of this exact behavior seems unlikely without adding to ckanext-spatial directly.

1. adding spatial boundaries while there is an existing rectangle or circle should be disabled, currently even if there is a rectangle or circle the user can still add boundaries.

**Comment by Mohab25** [comment]
@seabilwe @Jeremy-Prior @ThiashaV ,  i'm leaving closing this issue and tick off @gubuntu remarks for the result of your test, please examine and close (or tick off) accordingly.

**Comment by Jeremy-Prior** [comment]
- the map components take a while to load on first page load:
The map loads almost simultaneously with the page's first load: 
![InstantaneousLoad](https://user-images.githubusercontent.com/100694811/204291224-006f4f6a-9863-4ac9-9315-2de2684f4ae5.gif)
The speed with which the map loads may be affected by internet connection speed because this is with a slower connection:
![MapComponentLoad](https://user-images.githubusercontent.com/100694811/204258174-c48d2f94-d377-4075-83d8-a14adac9ca1b.gif)

- the 'expand' control needs a tooltip to say what it's for:
Has this been removed? The map automatically expands when a user selects the rectangular search or searches by proximity.

- when expanding, the map should match the width of and align with the other page elements, which it doesn't do right now:
The map now matches the width of and aligns with other page elements:
![EdgeToEdgeMap](https://user-images.githubusercontent.com/100694811/204292290-3b2174a4-9dd2-463c-a686-0bccbdab7403.gif)

- there should not be blank space when the map expands. It should centre on SA or wherever the user has zoomed and continue with map content to the edge of the canvas (like it does after you click the edit icon):
Fixed in PR #383:
![ExpandingMap](https://user-images.githubusercontent.com/100694811/204293148-22f92f60-65b4-4d39-b484-1c964ecbec0a.gif)

- after digitising a rectangle, the apply button overlaps the section below, please polish the placement:
Fixed on testing site:
![RectangularApply](https://user-images.githubusercontent.com/100694811/204293412-8d233ba3-f209-4718-82a5-7d5e7f1029a7.gif)

- the thick blue boundary style doesn't look great:
Working on mock up / inspiration.

- each layer should be mutually exclusive i.e. radio buttons rather than check boxes. Right now it's possible to draw all four layers which gets messy:
Already implemented on the testing site.
![LayerSearch](https://user-images.githubusercontent.com/100694811/204257504-f7d3cc60-b01b-460f-86ec-0635fe92efe9.gif)

- how does one do a proximity search? (RF04c):
A user clicks on the circle button, then clicks and drags from a point on the map to make a circular buffer of a desired size.
![ProximitySearch](https://user-images.githubusercontent.com/100694811/204294758-703f76aa-5c13-43ee-888e-513eca7ae5f2.gif)

**Comment by Jeremy-Prior** [comment]
@Mohab25 potential mock styling:
![MockupStyle](https://user-images.githubusercontent.com/100694811/204299724-e4341a79-1e87-4339-bdf8-64a5e4e6af53.png)

**Comment by Mohab25** [comment]
notice the tooltip over the rectangle (it shows when a user hovers over the rectangle)
![rectangle search hint](https://user-images.githubusercontent.com/58084234/204348426-8dc7f3dd-8556-4594-aa3a-244fd65881fa.png)
the closet color for the previous mock i found appealing is #008000, now implemented, please give a mock if you feel would appear better 
![new geojson style](https://user-images.githubusercontent.com/58084234/204348439-772257f2-f462-4647-a55c-01ee7fd2b20c.png)

**Comment by Jeremy-Prior** [comment]
Tooltips present on testing site:
![ToolTip](https://user-images.githubusercontent.com/100694811/204497571-befba373-4795-49e8-850a-ce29408a69e9.gif)

@Mohab25 The colour looks good, is it possible to make the border lines thinner? When the map isn't expanded and "Municipal Districts" or "Local Municipalities" are selected the thick lines are a bit overbearing:
![ThickLines](https://user-images.githubusercontent.com/100694811/204498175-84ca4a4c-5c76-42b1-b728-b1dd61f2e1dc.png)

**Comment by Jeremy-Prior** [comment]
Thinner lines implemented, looks great @Mohab25:
![LinesFixed](https://user-images.githubusercontent.com/100694811/204751234-c815e505-a664-4bd4-8179-59890a30c363.png)
