### ISSUE TITLE
search with a search term, then delete it and apply a filter and the search term reappears. It should remain deleted so the search is not reapplied.

### ISSUE THREAD

**Issue by Fanevanjanahary** [kartoza/ckanext-dalrrd-emc-dcpr#372]

**Comment by Mohab25** [comment]
fixed with ##352

**Comment by Jeremy-Prior** [comment]
The way I interpret this issue is that a user types a term into the search bar and searches for it. The user then deletes the term in the search bar and applies a filter from the available options on the left hand side of the page. When the user deletes the search term and applies the filter the term should remain deleted so that the search condition is not reapplied. Currently when the user deletes the search term and applies a filter the search term reappears. 

- Using the search term and then clearing it causes the search term to reappear when a filter is selected, this makes sense to me when you need to apply multiple filters to a searched term:
![1_SearchTerm](https://user-images.githubusercontent.com/100694811/205016204-141bacd1-8bd0-4bf1-9488-fa70ecc843c8.gif)

- The way to clear the searched term is to delete the term and then click enter/search and make a blank search. 
![2_ClearedSearch](https://user-images.githubusercontent.com/100694811/205017797-5bab8317-4c26-4cfd-9d8c-953159b709c7.gif)

- To address this issue, would it be possible to make a way to clear the searched term (i.e. a little 'x' like is applied for the other filters) instead of having to do a blank search? Otherwise a tip beneath the search bar could say something like "To search all records clear the term in the search bar and click search"
![3_XtoClearpng](https://user-images.githubusercontent.com/100694811/205018816-ed76d8d0-be5a-4128-9103-b0841d1b536c.png)

**Comment by Mohab25** [comment]
the current behavior is that when a user clear the search term and subsequently applies a filter before click search or press enter, the search term is not appearing in the next search and only the filter applies:
`When the user deletes the search term and applies the filter the term should remain deleted so that the search condition is not reapplied. Currently when the user deletes the search term and applies a filter the search term reappears.`
e.g the following "version" search term is used and gives 68 results:

![version-seach-term](https://user-images.githubusercontent.com/58084234/207910222-e6bdecb0-de2b-4a56-bf75-d9197a2cb458.png)

once the terms is deleted and a new facet is subsequently used before making a search, e.g. iso category "society"  and then making a search, the previous terms is deleted and the iso topic is searched, results 16 (currently there is another irrelevant issue that the active search is not highlighted):

![society-iso-topic](https://user-images.githubusercontent.com/58084234/207910301-a301ba6f-4c4f-4f8d-971c-81d3b7aecbf1.png)

other suggestions are great, please open a new ticket with the next stabilisation milestone if you see they still hold.

**Comment by Jeremy-Prior** [comment]
When a user deletes the search term in search bar and then applies another filter, the site only returns results for the filter and doesn't apply the search term again.
![4_fixed](https://user-images.githubusercontent.com/100694811/208697594-5676d67c-2f15-4a87-b7fc-3cbdfba771fe.gif)
