### ISSUE TITLE
dataset to metadata record

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#398]
there are still cases of 'dataset' instead of 'metadata record' and 'data' instead of 'links'

![Screenshot 2022-12-01 at 12 46 06](https://user-images.githubusercontent.com/496911/205033461-2dcd0fa0-08c8-4321-9eb3-8971be77efb5.png)

**Comment by Mohab25** [comment]
![Metadata record](https://user-images.githubusercontent.com/58084234/207889488-ec7bf56f-602a-42e0-a66e-79377b963ac1.png)

**Comment by Jeremy-Prior** [comment]
@Mohab25 Apologies, no idea how I missed these first two previously, on the 'create metadata record' and 'edit metadata' pages on the staging site there are still instances of "dataset".
'Create metadata record' page:
![image](https://user-images.githubusercontent.com/100694811/208689483-3a91c53f-db0a-45ed-8c55-b2466cdc2011.png)
'Edit metadata' page:
![image](https://user-images.githubusercontent.com/100694811/208689632-a36b86eb-e6e5-4f83-81b0-9960112acfdb.png)

There are also multiple instances of "dataset" in the subtext descriptors on both pages. e.g.: 
![image](https://user-images.githubusercontent.com/100694811/208691266-ce61b979-5c4f-49d4-bf8a-585ad2c96497.png)
List of the instances of dataset:
- [ ]  Name by which the cited resource is known, the automatically filled URL is a unique identifier for the dataset - This is a SANS 1878 mandatory field 
- [ ]  Should this dataset be featured on the EMC front page? 
- [ ]  Brief description why this dataset is created - This is a SANS 1878 mandatory field 
- [ ]  Recognition of those who contributed to the dataset 
- [ ]  Status of the dataset- This is a SANS 1878 mandatory field 
- [ ]  Organization responsible for the dataset. This is a SANS 1878 mandatory field 
- [ ]  name - with surname of the person responsible of this dataset 
- [ ]  Reference date for this dataset - This is a SANS 1878 mandatory field 
- [ ]  ISO 19115 Topic Category for the dataset - This is a SANS 1878 mandatory field 
- [ ]  Additional keywords useful for describing the dataset. In order to optimize searchability, it is recommended to add at least three keywords 
- [ ]  Dataset version:
- [ ]  Dataset language:
- [ ]  Language for the dataset - This is a SANS 1878 mandatory field 
- [ ] Dataset character set:
- [ ]  Full name of the character coding standard used for the dataset - This is a SANS 1878 mandatory field 
- [ ]  Full name of the character coding standard used for the dataset - This is a SANS 1878 mandatory field 
- [ ]  general explaination of the data producer's knowledge about the lineage of a dataset - This is a SANS 1878 mandatory field (_also need to change the spelling of explanation in this subtext_)
- [ ]  name - with surname of the person responsible of processing this dataset 
- [ ]  Organization responsible for processing the dataset 
- [ ]  information about how the dataset may be obtained, and related instructions and fee information 
- [ ]  "Name of the individual responsible for the dataset. Provide it in the following format: surname, given name, title separated by a delimiter" 
- [ ]  frequency with which changes and additions are made to the dataset after it's submitted 
- [ ]  additional information about the range or extent of the dataset 
- [ ]  Bounding box for the dataset, expressed as the geographic coordinates of the upper left and lower right corners - This is a SANS 1878 mandatory field 
- [ ]  "Name of spatial reference system. Provide it as a colon-separated sequence of <ref>:<code> with the respective code for the dataset's spatial coordinate reference system. It is recommended to use the EPSG spatial catalogue codes whenever possible (e.g. EPSG:32635). Alternatively it is recommended to use a reference as shown on the www.spatialreference.org website, which features EPSG, ESRI and user-defined references to well-known coordinate reference systems - This is a SANS 1878 mandatory field"

**Comment by Mohab25** [comment]
@Jeremy-Prior new PR handles these, it usually takes 2 hours to reflect, check and close accordingly

**Comment by Jeremy-Prior** [comment]
@Mohab25 I just checked the staging site, the changes haven't reflected yet. I will check again later.

**Comment by Mohab25** [comment]
@Jeremy-Prior please check the testing site, as tharanath i currently on leave, these changes aren't pulled to staging yet, if things are satisfactory with testing, please close this issue.

**Comment by Jeremy-Prior** [comment]
@Mohab25 checked the testing site, just one final subtext that needs to be changed and then this can be closed.
- [ ] Name by which the cited resource is known, the automatically filled URL is a unique identifier for the dataset - This is a SANS 1878 mandatory field

**Comment by Fanevanjanahary** [comment]
Hi @Jeremy-Prior, can you please test this?

**Comment by Jeremy-Prior** [comment]
I checked and the final instance of 'dataset' that I was aware of has been changed to 'metadata record'.
