### ISSUE TITLE
thumbnails

### ISSUE THREAD

**Issue by gubuntu** [kartoza/ckanext-dalrrd-emc-dcpr#399]
Each record is supposed to have a thumbnail image, which the metadata editor must add. Where and how can they do this? 

Once a thumbnail is provided it should appear in the metadata list page and in the metadata record detail view. 

Thumbnails should be forced into a standard size and aspect ratio.

**Comment by Mohab25** [comment]
@gubuntu to avoid a case where the storage of such thumbnails conflicts with the idea that we aren't storing anything with locally with EMC, the user could provide a thumbnail url in a record in the metadata form, taking this link then we can preview the image a mockup would follow,

**Comment by gubuntu** [comment]
Ideally a thumbnail should be available as a link (say a WMS). If a WMS Resource link is provided, the system can request an image of the right size (and full extent) to render in the thumbnail div.  This should be cached locally and only rerequested if the record changes.

However I'm sure we will need to cater for locally stored (manually uploaded) thumbnails, since many (most) records will not have WMS links. How can we do that outside the 'Resources' framework?

Final say should be with the client, please check.

**Comment by Mohab25** [comment]
by providing them in a metadata record level not resource one via creating a new field in the form to hold the thumbnail in a form of url, thumbnails can be of any image type (png, jpg, ..etc.) and not reduced only to be of WMS type, the only question is that should we be concerned about the storage? if not, the user could simply provide a link. 
`However I'm sure we will need to cater for locally stored (manually uploaded) thumbnails, since many (most) records will not have WMS links. How can we do that outside the 'Resources' framework?`

![thumbnail metadata field ](https://user-images.githubusercontent.com/58084234/207924857-bcb267a4-c882-40c9-9f3d-c1a015ab37d1.png)

the following is https://files.isric.org/public/thumbnails/afsis250m/clyppt.png

![url thumbnail preview](https://user-images.githubusercontent.com/58084234/207925290-f0123ed9-5502-4050-a9f9-0fedfea5cbb3.png)


sure,
`Final say should be with the client, please check.`

**Comment by faizalprbw** [comment]
since the width and height of thumbnail div are 150px x 150px. So the best ratio for image thumbnail is 1:1, as long as they have the same width and height, it will return propositional.
![image](https://user-images.githubusercontent.com/7609337/210789117-f99b164c-c383-40ec-8808-afe13b4f7d4a.png)

In [PR](https://github.com/kartoza/ckanext-dalrrd-emc-dcpr/pull/425), I add `Use images with 1:1 ratio for better results` to help text:

![image](https://user-images.githubusercontent.com/7609337/210789950-bdce7e82-1f09-4ddc-b06a-c7992614f3fe.png)

**Comment by ThiashaV** [comment]
Adding a thumbnail when creating a record works as intended
![image](https://user-images.githubusercontent.com/98025261/212266923-b10653b0-fc73-49f9-9b2f-ef1c036b0eb3.png)
 @faizalprbw I think it should be specified that the link needs to be a public link and cannot be a private one as the thumbnail does not load if it's private.

**Comment by faizalprbw** [comment]
@ThiashaV should we add this explanation to help text?

**Comment by ThiashaV** [comment]
@faizalprbw will do!
