### ISSUE TITLE
Set up staging environment

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#41]
More details to come soon...

**Comment by gubuntu** [comment]
@tharanathkartoza please comment on issues that have been assigned to you and manage their status in the project board

**Comment by gubuntu** [comment]
The staging site was fully and successfully deployed to DALRRD infrastructure on 24 August and has been available internally and via VPN ever since. 

As soon as the OCIO has provided a public IP and ingress routing has been configured, Kartoza will configure https://staging.emc.kartoza.com/ to point to it.

DALRRD is also welcome to configure a domain such as https://staging.sasdi.net, but that is beyond Kartoza's control.

**Comment by Jeremy-Prior** [comment]
the staging site is available at: https://testing.emc.kartoza.com/
![image](https://user-images.githubusercontent.com/100694811/201101955-1eac710a-dbd2-4bb0-aa29-c53fad5b6144.png)

**Comment by gubuntu** [comment]
no that is the testing site, not the staging site. The staging site is running on DALRRD infrastructure but is not public yet. What's the latest @tharanathkartoza ?

**Comment by gubuntu** [comment]
so let's close this when the staging site is public and ready to host UAT

**Comment by tharanathkartoza** [comment]
staging site has been setup except pycsw domain and ssl certificate.

**Comment by Mohab25** [comment]
currently we have UAT happening over the staging site, the last point @tharanathkartoza made about this issue is found across other tickets.
