### ISSUE TITLE
Buttons to request being an NSIF and CSI reviewer 

### ISSUE THREAD

**Issue by ThiashaV** [kartoza/ckanext-dalrrd-emc-dcpr#454]
all organisation members should have the option to request to be a NSIF or CSI reviewer once they are a part of the NSIF and/or CSI organisations (R6 and R7). 

there should also be a way to request being a portal content manager 
@seabilwe

**Comment by Mohab25** [comment]
@ThiashaV the first part of this issue (NSIF-CSI reviews) is handled, the second part (content manager) is more of a policy than technical side, specific system-admins can be assigned as content managers, due to how the site extend some of it's plugins ([ckanext-pages](https://github.com/ckan/ckanext-pages)) content managers role cannot be separated from system-admins.
