### ISSUE TITLE
Number of records associated with SASDI themes is not accurate.

### ISSUE THREAD

**Issue by Jeremy-Prior** [kartoza/ckanext-dalrrd-emc-dcpr#482]
When there are 0 records associated with a SASDI theme, the site still displays an incorrect number.
E.g.:
- The 'Administrative Boundaries 1' theme shows 7 associated records 
![SASDIThemes_1](https://user-images.githubusercontent.com/100694811/217170417-a78fe219-80e5-4cf7-a1ea-8c3b591a56d1.png)
- However, when the theme is selected 0 records are found
![SASDIThemes_2](https://user-images.githubusercontent.com/100694811/217170676-1e1576de-533f-4263-b1c3-1ac7aeb7fda4.png)

When a SASDI theme actually has associated records, the number reflected on the site appears to be correct.

**Comment by Mohab25** [comment]
this been fixed with #499, the testing site is now showing correct records and numbering with SASDI themes, @gubuntu although assigned to Faneva, it required working with SOLR to update the numbers, cc @Jeremy-Prior i've gave @tharanathkartoza a heads up about pulling to staging, once it there, give it a test and close accordingly

**Comment by Jeremy-Prior** [comment]
@Mohab25 This is fixed
Anonymous user on left and a registered user on the right:
![issue482_1](https://user-images.githubusercontent.com/100694811/220928279-19bb5070-15ae-49d1-b3f5-0cb442f48458.png)
Numbers match exactly:
![issue482_2](https://user-images.githubusercontent.com/100694811/220928330-46efe2e6-aa18-4c7f-9224-dee363f64ea7.png)
