### ISSUE TITLE
Integrate CKAN datapusher service into dev stack

### ISSUE THREAD

**Issue by ricardogsilva** [kartoza/ckanext-dalrrd-emc-dcpr#59]
The CKAN datastore extension works together with the [datapusher](https://github.com/ckan/datapusher) service in order to automatically extract relevant data from existing datasets.

Integrate this into the dev stack by adapting the installation instructions into a container-based deployment method.

**Comment by Mohab25** [comment]
@gubuntu as per the [datapusher](https://github.com/ckan/datapusher) definition, it extracts data from CSV-like files and stores them into CKAN datastore which is a second database enabled with CKAN, this is irrelevant to the EMC as it's a metadata clearinghouse and it doesn't store any files, thus closing this issue, if you think otherwise please reopen and tag me in a comment,

**Comment by gubuntu** [comment]
agreed

(but it looks like something we could have used in WRO?)

**Comment by Jeremy-Prior** [comment]
Per @Mohab25's comment:
> it extracts data from CSV-like files and stores them into CKAN datastore which is a second database enabled with CKAN, this is irrelevant to the EMC as it's a metadata clearinghouse and it doesn't store any files
